# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: traffic.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtraffic.proto\x12\x0etrafficcontrol\"0\n\x0cStateRequest\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"1\n\nStateReply\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x12\n\nerror_code\x18\x02 \x01(\t\"k\n\x0eRefreshRequest\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x0c\n\x04time\x18\x02 \x01(\x05\x12\x10\n\x08phase_id\x18\x03 \x01(\x05\x12\x17\n\x0fintersection_id\x18\x04 \x01(\t\x12\x0f\n\x07\x61pi_key\x18\x05 \x01(\t\"A\n\x0cRefreshReply\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x0c\n\x04time\x18\x02 \x01(\x05\x12\x12\n\nerror_code\x18\x03 \x01(\t\"\xc4\x01\n\x10\x44\x61taTransmission\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x17\n\x0fintersection_id\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12:\n\x07\x65ntries\x18\x04 \x03(\x0b\x32).trafficcontrol.DataTransmission.KeyValue\x12\x0f\n\x07\x61pi_key\x18\x05 \x01(\t\x1a&\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05\">\n\tDataReply\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x0c\n\x04time\x18\x02 \x01(\x05\x12\x12\n\nerror_code\x18\x03 \x01(\t2\xf4\x01\n\rTrafficServer\x12G\n\tSendState\x12\x1c.trafficcontrol.StateRequest\x1a\x1a.trafficcontrol.StateReply\"\x00\x12K\n\tHeartBeat\x12\x1e.trafficcontrol.RefreshRequest\x1a\x1c.trafficcontrol.RefreshReply\"\x00\x12M\n\x0cTransmitData\x12 .trafficcontrol.DataTransmission\x1a\x19.trafficcontrol.DataReply\"\x00\x42<\n\x1dio.grpc.modules.trafficserverB\x12TrafficServerProtoP\x01\xa2\x02\x04\x43HSRb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'traffic_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\035io.grpc.modules.trafficserverB\022TrafficServerProtoP\001\242\002\004CHSR'
  _STATEREQUEST._serialized_start=33
  _STATEREQUEST._serialized_end=81
  _STATEREPLY._serialized_start=83
  _STATEREPLY._serialized_end=132
  _REFRESHREQUEST._serialized_start=134
  _REFRESHREQUEST._serialized_end=241
  _REFRESHREPLY._serialized_start=243
  _REFRESHREPLY._serialized_end=308
  _DATATRANSMISSION._serialized_start=311
  _DATATRANSMISSION._serialized_end=507
  _DATATRANSMISSION_KEYVALUE._serialized_start=469
  _DATATRANSMISSION_KEYVALUE._serialized_end=507
  _DATAREPLY._serialized_start=509
  _DATAREPLY._serialized_end=571
  _TRAFFICSERVER._serialized_start=574
  _TRAFFICSERVER._serialized_end=818
# @@protoc_insertion_point(module_scope)
